### ISSUE TITLE
query strings with & ?

### ISSUE THREAD

**Issue by ralphtheninja** [deanlandolt/query-schema#1]
Does

`qss.parse('?name=The+Big+Lebowski;year=1998')`

work the same way as

`qss.parse('?name=The+Big+Lebowski&year=1998')`

?

**Comment by deanlandolt** [comment]
``` js
const qss = require('@query/schema/querystring')

qss.parse('?name=The+Big+Lebowski;year=1998')
// {
//   "allOf": [
//     {
//       "properties": {
//         "name": {
//           "constant": "The Big Lebowski"
//         }
//       }
//     },
//     {
//       "properties": {
//         "year": {
//           "constant": "1998"
//         }
//       }
//     }
//   ]
// }

qss.parse('?name=The+Big+Lebowski&year=1998')
// SyntaxError: Expected ",", ";" or end of input but "=" found.
```

I think I'd planned to support `&` as top level low-precedence conjunction (w/ `;` being high-precedence conjunction), but it doesn't quite hold together as well as I'd like. So for now there's just `;` for conjunction -- and parentheses, which go a long way.

**Comment by ralphtheninja** [comment]
Cool. Thanks for reply! :)
